[package]
name = "cli-rs"
version = "0.2.0"
edition = "2021"
license = "Unlicense"
description = "create clis with sophisticated completions"

[dependencies]
colored = "2"
cli-rs-command-gen = "0.1.12"

[workspace]
resolver="2"
members = [
    "",
    "src/command/cli-rs-command-gen"
]
